name: material3_rail_drawer
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_use: ^0.0.3
  go_router: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  equatable_lint: ^0.2.1

flutter:
  uses-material-design: true
